// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
insert into posts(id, created_at, updated_at, published_at, title, url, description, feed_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePostParams struct {
	ID          uuid.UUID `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	PublishedAt time.Time `json:"published_at"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
	Description string    `json:"description"`
	FeedID      uuid.UUID `json:"feed_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg *CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
	)
	return err
}

const getPostByUrl = `-- name: GetPostByUrl :one
select id, created_at, updated_at, published_at, title, url, description, feed_id
from posts
where url in ($1)
`

func (q *Queries) GetPostByUrl(ctx context.Context, url string) (*Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByUrl, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
	)
	return &i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
select posts.id,
       posts.created_at,
       posts.updated_at,
       posts.published_at,
       posts.title,
       posts.url,
       posts.description,
       posts.feed_id
from feed_follows
         inner join feeds on feed_follows.feed_id = feeds.id
         inner join posts on feeds.id = posts.feed_id
where feed_follows.user_id = $1
limit $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg *GetPostsForUserParams) ([]*Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
